version: '3.4'

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:-quay.io/api-platform/nginx}
      - ${PHP_IMAGE:-quay.io/api-platform/php}

services:
  traefik:
    image: traefik:v2.0
    command: --api.insecure --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  php:
    build:
      context: ../api-platform-2.5.0/api
      target: api_platform_php
      <<: *api-cache-from
    image: ${PHP_IMAGE:-quay.io/api-platform/php}
    depends_on:
      - db
    volumes:
      - ../api-platform-2.5.0/api:/srv/api:rw,cached
      - ../api-platform-2.5.0/api/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini

  api:
    build:
      context: ../api-platform-2.5.0/api
      target: api_platform_nginx
      <<: *api-cache-from
    image: ${NGINX_IMAGE:-quay.io/api-platform/nginx}
    depends_on:
      - php
    volumes:
      - ../api-platform-2.5.0/api/public:/srv/api/public:ro
    labels:
      - traefik.http.routers.api.rule=Host(`api.domain.com`)

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-platform
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    labels:
      - traefik.http.routers.db.rule=Host(`db.domain.com`)

  mercure:
    image: dunglas/mercure
    environment:
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - DEMO=1
      - JWT_KEY=!ChangeMe!
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337,https://localhost:1338
    labels:
      - traefik.http.routers.mercure.rule=Host(`mercure.domain.com`)

  client:
    build:
      context: ../api-platform-2.5.0/client
      target: api_platform_client_development
      cache_from:
        - ${CLIENT_IMAGE:-quay.io/api-platform/client}
    image: ${CLIENT_IMAGE:-quay.io/api-platform/client}
    environment:
      - API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT=http://api
      - API_PLATFORM_CLIENT_GENERATOR_OUTPUT=src
      - REACT_APP_API_ENTRYPOINT=http://api.domain.com
    volumes:
      - ../api-platform-2.5.0/client:/usr/src/client:rw,cached
    labels:
      - traefik.http.routers.client.rule=Host(`domain.com`, `www.domain.com`)

  admin:
    build:
      context: ../api-platform-2.5.0/admin
      target: api_platform_admin_development
      cache_from:
        - ${ADMIN_IMAGE:-quay.io/api-platform/admin}
    environment:
      - REACT_APP_API_ENTRYPOINT=http://api.domain.com
    image: ${ADMIN_IMAGE:-quay.io/api-platform/admin}
    volumes:
      - ../api-platform-2.5.0/admin:/usr/src/admin:rw,cached
    labels:
      - traefik.http.routers.admin.rule=Host(`admin.domain.com`)

volumes:
  db-data: {}
