version: '3.4'

x-cache:
  &cache
  cache_from:
    - ${CONTAINER_REGISTRY_BASE}/php
    - ${CONTAINER_REGISTRY_BASE}/nginx
    - ${CONTAINER_REGISTRY_BASE}/varnish

services:
  traefik:
    image: traefik:v2.0
    command: --api.insecure --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ../api-platform-2.4.6/api
      target: api_platform_php
      <<: *cache
    depends_on:
      - db
    volumes:
      - ../api-platform-2.4.6/api:/srv/api:rw,cached

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ../api-platform-2.4.6/api
      target: api_platform_nginx
      <<: *cache
    depends_on:
      - php
    volumes:
      - ../api-platform-2.4.6/api/public:/srv/api/public:ro
    labels:
      - traefik.http.routers.api.rule=Host(`api.domain.com`)

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    build:
      context: ../api-platform-2.4.6/api
      target: api_platform_varnish
      <<: *cache
    depends_on:
      - api
    volumes:
      - ../api-platform-2.4.6/api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    labels:
      - traefik.http.routers.cache-proxy.rule=Host(`cache.domain.com`)

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY=!ChangeMe!
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337,https://localhost:1338
      - DEMO=1
    labels:
      - traefik.http.routers.mercure.rule=Host(`mercure.domain.com`)

  client:
    image: ${CONTAINER_REGISTRY_BASE}/client
    build:
      context: ../api-platform-2.4.6/client
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/client
    env_file:
      - ../api-platform-2.4.6/client/.env
    volumes:
      - ../api-platform-2.4.6/client:/usr/src/client:rw,cached
      - ../api-platform-2.4.6/client/node_modules:/usr/src/client/node_modules
    expose:
      - 3000
    labels:
      - traefik.http.routers.client.rule=Host(`domain.com`)

  admin:
    image: ${CONTAINER_REGISTRY_BASE}/admin
    build:
      context: ../api-platform-2.4.6/admin
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/admin
    volumes:
      - ../api-platform-2.4.6/admin:/usr/src/admin:rw,cached
      - ../api-platform-2.4.6/admin/node_modules:/usr/src/admin/node_modules
    expose:
      - 3000
    labels:
      - traefik.http.routers.admin.rule=Host(`admin.domain.com`)

volumes:
  db-data: {}
